'use client'

import React from 'react'
import { Download, FileText, Map, ShieldCheck, FileCheck, ExternalLink } from 'lucide-react'

const OFFICIAL_DOCUMENTS = [
  {
    id: 'doc-map',
    title: 'Official Park Map & Track Brochure (2025/2026)',
    desc: 'High-resolution topographic guide with GPS waypoints, ranger gates, campsites, and wildlife loops.',
    type: 'PDF • 4.2 MB',
    icon: Map,
    badge: 'Essential Guide',
  },
  {
    id: 'doc-checklist',
    title: 'Comprehensive Wildlife & Bird Species Checklist',
    desc: 'Complete taxonomic catalog of 450+ mammals, raptors, endemics, and reptiles recorded in Borana NP.',
    type: 'PDF • 1.8 MB',
    icon: FileText,
    badge: 'Biodiversity Index',
  },
  {
    id: 'doc-rules',
    title: 'Park Regulations & Ethical Wildlife Code',
    desc: 'Mandatory ministerial rules for self-drive expeditions, campfire safety, drone restrictions, and scout protocol.',
    type: 'PDF • 850 KB',
    icon: ShieldCheck,
    badge: 'Legal Requirements',
  },
  {
    id: 'doc-research',
    title: 'Scientific Research & Filming Permit Application',
    desc: 'Official EWCA application protocols for academic fieldwork, biological sample collection, and commercial media.',
    type: 'PDF • 1.2 MB',
    icon: FileCheck,
    badge: 'Permits Form',
  },
]

export default function OfficialDownloads() {
  const handleDownload = (title: string) => {
    alert(`Downloading official document: "${title}". (Digital archive generated by Ethiopian Wildlife Conservation Authority)`)
  }

  return (
    <div className="bg-white rounded-2xl border border-sand-200 p-6 sm:p-8 shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-sand-200 pb-5 mb-6">
        <div>
          <span className="text-xs uppercase tracking-wider text-gold-600 font-semibold">Government Publications</span>
          <h3 className="text-2xl font-display font-semibold text-charcoal-900">Official Downloads & Resources</h3>
        </div>
        <span className="text-xs font-medium text-forest-800 bg-forest-100 px-3 py-1 rounded-full">
          Authorised EWCA Public Library
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {OFFICIAL_DOCUMENTS.map(doc => (
          <div
            key={doc.id}
            className="border border-sand-200 hover:border-forest-700/50 rounded-xl p-5 hover:bg-sand-50/40 transition-all flex flex-col justify-between group"
          >
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] uppercase font-bold tracking-wider text-forest-800 bg-forest-100 px-2 py-0.5 rounded">
                  {doc.badge}
                </span>
                <span className="text-xs text-charcoal-700 font-mono">{doc.type}</span>
              </div>
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-lg bg-forest-100/70 text-forest-800 flex items-center justify-center flex-shrink-0 group-hover:bg-forest-800 group-hover:text-white transition-colors">
                  <doc.icon className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-display font-semibold text-charcoal-900 text-base leading-snug group-hover:text-forest-900">
                    {doc.title}
                  </h4>
                  <p className="text-xs text-charcoal-700 mt-1.5 leading-relaxed">
                    {doc.desc}
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-5 pt-3 border-t border-sand-200 flex justify-end">
              <button
                onClick={() => handleDownload(doc.title)}
                className="inline-flex items-center gap-1.5 text-xs font-semibold text-forest-800 hover:text-forest-950 bg-forest-50 hover:bg-forest-100 px-3.5 py-1.5 rounded-lg border border-forest-200 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Document</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
